name: Repository Dispatch
on:
  repository_dispatch:
    types: [deploy]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
      MIQ_ENV: production
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5'
          bundler-cache: true
      - name: Get manageiq.org repo
        run: git clone https://github.com/ManageIQ/manageiq.org
      - name: Build
        run: cd manageiq.org & exe/miq build all
      - name: Deploy
        run: ./deploy.sh
      #   with:
      #     ref: ${{ github.event.client_payload.ref }}
      # - run: echo ${{ github.event.client_payload.sha }}