name: Build
on:
  repository_dispatch:
    types: [deploy]
  schedule:
  - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: production
      MIQ_ENV: production
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PAYLOAD_REF_NAME: ${{ github.event.client_payload.ref_name }}
      PAYLOAD_SHA: ${{ github.event.client_payload.sha }}
      PAYLOAD_REPOSITORY: ${{ github.event.client_payload.repository }}
      PAYLOAD_PR_NUMBER: ${{ github.event.client_payload.pr_number }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Get manageiq.org repo
        run: git clone https://github.com/ManageIQ/manageiq.org
      - name: Build
        run: |
          cd manageiq.org
          bundle install
          exe/miq build all
      - name: Deploy
        run: bin/deploy
